-- 1
SELECT CLI_NOM, T_CLIENT.CLI_ID, count(TJ_CHB_PLN_CLI.CLI_ID) as NB_OCCUP
FROM T_CLIENT, TJ_CHB_PLN_CLI
WHERE T_CLIENT.CLI_ID = TJ_CHB_PLN_CLI.CLI_ID
Group by CLI_NOM
ORDER BY NB_OCCUP desc

--2
SELECT CLI_NOM,              T_CLIENT.CLI_ID,                      sum(T_LIGNE_FACTURE.FAC_ID) as total_depense
FROM T_CLIENT, T_LIGNE_FACTURE, T_FACTURE
WHERE T_CLIENT.CLI_ID = T_FACTURE.CLI_ID
AND T_FACTURE.FAC_ID = T_LIGNE_FACTURE.FAC_ID
Group by CLI_NOM
ORDER BY total_depense desc

--3

--4
--5
Select LIF_REMISE_POURCENT as Remise_en_Pourcent,
LIF_REMISE_MONTANT as Remise_en_euro,
LIF_MONTANT as Montant_HT,
LIF_TAUX_TVA as TVA,
LIF_ID,

sum(LIF_MONTANT * ((100- LIF_TAUX_TVA)/100) ) as total
--sum(LIF_MONTANT * LIF_TAUX_TVA  / (1*LIF_REMISE_POURCENT)- LIF_REMISE_MONTANT)


FROM T_LIGNE_FACTURE

GROUP BY LIF_ID


--6
